### ISSUE TITLE
system requirement 

### ISSUE THREAD

**Issue by bestasok** [KhelkudNepal/KhelkudWeb#1]
## SYSTEM REQUIREMENTS

This is a sports-based web platform for province no. 3. There are 13 districts in this province. 
Format Eg.
```
district: Sindhuli,
sports_category: Football,
team/club: Laliguras club,
players, 
coaches 
referee
...
```
Information should be stored district wise, category wise and club wise.
    1. Players Profile
    2. Coach or Referee Profile
    3. Results of Match
    4. Rating of players – based on nature & level of player
    5. Biography of nationally & internationally awarded players
    6. Highlight respected players (Top-rated players)
    7. Multi-user/ roles & permission-based
    8. In-site and out-site search (Nepali, English both) Eg. Search feature for players
    9. News/Events based on district and sports category
    10. Latest news highlights
    11. Locate 13 districts in map and filter information according to the selected district
    12.  Information of sports infrastructure in each district ( like name of ground, other sports related infrastructure details )
    13. Form submission to email ( like a contact form )

**Comment by kiranparajuli589** [comment]
@bestasok details about what permission does each roles have is needed

**Comment by pratima99** [comment]
On permission issue , I will inform you tomorrow.

**Comment by pratima99** [comment]
@kiranparajuli589  @surazad99 

Province Office - Super Admin - Has all permission 
District Office - Admin - Give permission to users & have permission to CRUD
Data entry users (of both province and district level) -  Have permission to create and update
Players - Can modify their content and modify request should be approved by admin

**Comment by kiranparajuli589** [comment]
not required form now!
