### ISSUE TITLE
Ideas about landing page and newsFeed page

### ISSUE THREAD

**Issue by kiranparajuli589** [KhelkudNepal/KhelkudWeb#26]
Clarification about landing page and newsFeed page required!

- what contents to show?
- when and where to show?
- who can see?

**Comment by pratima99** [comment]
News feed page will be a different page where all news will be shown in grid layout. Landing page will contain Latest News, Top rated players, Featured Match, Featured News in grid layout( like 4 news), Results of match, Search Bar, etc

**Comment by pratima99** [comment]
Just be clear that we all normal users can view the site without login. Login system is for district representatives, players, data entry users where permissions will be given according to their roles. All added content in the database will be displayed in the site which can be viewed by everyone.

**Comment by kiranparajuli589** [comment]
Okay :+1:  That is nice. @surazad99 Then IMO many getter APIs should be made without authentication.
