### ISSUE TITLE
Id required of created items in response

### ISSUE THREAD

**Issue by kiranparajuli589** [KhelkudNepal/KhelkudWeb#66]
Whenever some models are created using API, the `id` of the created item is needed in response for fluent frontend

example: successful sport create response as
```js
{
   message    : "Sport Created Successfully",
   code       : 201,
   item_created : {
       id: 1
       ...
   }
}

```

**Comment by surazad99** [comment]
kina chaiyo ra yoo?

**Comment by kiranparajuli589** [comment]
aarkai tarika le vayo! chaidaina aba
