### ISSUE TITLE
422 unprocessable entity while updating player

### ISSUE THREAD

**Issue by kiranparajuli589** [KhelkudNepal/KhelkudWeb#70]
Request with the following data:
![Screenshot from 2020-06-26 11-26-08](https://user-images.githubusercontent.com/39373750/85824593-e8b3c500-b79f-11ea-9070-be7b7c7d368e.png)

Got response as:
![Screenshot from 2020-06-26 11-27-39](https://user-images.githubusercontent.com/39373750/85824676-139e1900-b7a0-11ea-84e9-a5e9cec532a1.png)

**Comment by surazad99** [comment]
post method ma halepaxi ta _method ma PUT vanne value huna paryo ni ..........ki tha params ma halera pathauna parxa

**Comment by kiranparajuli589** [comment]
resolved
